/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hcmzhfakbupbpbhxgdmj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjbXpoZmFrYnVwYnBiaHhnZG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MTY3NDksImV4cCI6MjA3NzA5Mjc0OX0.8eQZ5IyVV2rNwLATGGJL-GhLh6nFBrqPw1Yew-L0kgc"